// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

int _Dimensions;
RWStructuredBuffer<float> _HeightMap;

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;

[numthreads(8,8,1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!

    Result[id.xy] = float4(_HeightMap[id.y * _Dimensions + id.x], 0, 0, 1);
}
